version: "3.8"

services:
  client:
    build:
      context: ./client
      target: production
    image: planninggpt-client:3.4
    container_name: planninggpt-client
    ports:
      - 3000:80
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    logging:
      options:
        max-size: "25m"
        max-file: "100"

  python-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: planninggpt-server-prod:3.4
    container_name: planninggpt-server-prod
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    command: gunicorn --workers 4 --threads 2 --timeout 120 --bind 0.0.0.0:5000 app:app --capture-output --access-logfile - --error-logfile - --log-level=info
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"
